# show_downloads: true
# google_analytics: G-GZNFK3DY0Z
theme: jekyll-theme-cayman
title: KuaiLive
description: "A real-world dataset for live streaming recommendation"
github:
  is_project_page: true